### PR TITLE
Visualforce documentation. Settings enhancement

### PR DESCRIPTION
**Pull request by maaaaarco**
Hi guys,
let me say thanks, before i start, this plugin is really awsome and save me a lot of time!

I added a couple of functionality here...
First of all, i added the method to download also Visualforce standard component references. I found it very useful when i have to deal with both Apex and Visualforce.

A little bit of code refactoring. I added two method, one to retrieve Apex documentation and the other for Visualforce one.

Added two settings in plugin's setting file to let users configure what kind of documentation to download.

What you think?

### CODE REVIEW

**Comment by maaaaarco** [comment]
I was trying to add also the Service Console Toolkit documentation but i had to stop right now

**Comment by Oblongmana** [comment]
@maaaaarco 

Nice! Having access to various different documentation types is something I'd discussed with one of my coworkers, we just hadn't worked out exactly the interface for it, or found the time yet. Will try to do a thorough review this in the next week or so, thanks!

At a quick glance over the code though: I'm not keen on having _all_ the reference entries (whether Apex, Visualforce, Service Console, or anything else we add) all in a single menu for a few reasons - mostly around possible overlap/clashes, ambiguity when selecting a reference entry, and just the sheer size the list will grow to. What I'd prefer is to split the "Salesforce Reference" command into 3 commands (or more, if we add other documentation types in future), each of which will present only the reference associated with that documentation type, so:
  - `Salesforce Reference - Apex` 
  - `Salesforce Reference - Visualforce`
  - `Salesforce Reference - Service Console`

Would you be able to update the PR to do this, or make any comments you want to?

**Comment by maaaaarco** [comment]
Yeah i was thinking that too! But because of time and work i wasn't able to do it.
I'll give it a try next weeks ;)

**Comment by maaaaarco** [comment]
@Oblongmana 
Give it a try now ;)
I added three different command to menu.
Now is possible to open different kind of documentation with different command. I also leave a command to show all downloaded documentation, it's useful sometimes and faster.

**Comment by Oblongmana** [comment]
Hey @maaaaarco - this works well for the most part. There are a couple of bugs that need working out, and a few changes I'd like to make, so I'm probably going to take a local copy of this to make those changes, and then push them up to master (so I'll wind up closing this PR, as I'll be doing the merge on my machine). I believe you'll still show up as a contributor in github, and I'll credit you specifically in the package control release notes when this is released. Will tag you once I'm done as well. Thanks again!

**Comment by maaaaarco** [comment]
Can't wait to see final release ;)
Meanwhile I'll be working on new docs to add later!

**Comment by AgingHippie** [comment]
I've been working with ApexDoc recently, it's an excellent tool.

I think adding a custom javadoc tag of @preview, usable in the javadoc comments on custom display controllers, might be a good approach to the issue of how to document VisualForce pages and improve the documentation of display controllers.  The tag would need to read and render the page, then convert the output to an image of some type and include it in the current page.

The solution for triggers might involve adding another level to the navigation menu on the main page, and another command line option to select the path to the triggers.  Beyond that, everything could work more or less as for classes, except that parsing logic would be needed to retrieve the trigger conditions.

I'm also writing documentation by hand for custom objects and custom fields on standard objects.  I think this information is in the metadata, along with comments that can be populated from SF setup.  A possible idea here would be to add another segment to the navigation menu at the top level for this information.

Apologies for just dropping a wish list instead of doing a pull and doing some of this stuff, but my Java is quite weak, I'm a .net programmer...

**Comment by Oblongmana** [comment]
Hey @AgingHippie - not 100% sure all of that comment is directed at this plugin?

The comments re an `@preview` tag were what make me think this should be a comment on the other project - that would DEFINITELY beyond the scope of what a Sublime Text editor plugin could do, not least of all because it would require modifications to the ApexDoc plugin. I suspect it would be technically nigh impossible regardless - while Visualforce is plainly derived from JSF, it isn't exactly the same, so you'd have to write your own renderer - then you have the issue of where the data comes from and so on, would be a very large metaphorical minefield!

For this plugin's scope though - I could certainly have a look at a possible integration with ApexDoc - but it requires Java, while this is a Sublime Text plugin where we don't have any guarantee the user has Java on their system. This could possibly be done as an optional extension to this plugin, or more realistically - as it a separate plugin. I'll put looking at this on the slow weekend list, but in short, it's possibly beyond the scope of this plugin. The most feasible route would be re-implementing ApexDoc in python, bundling it in with this, and then working out sensible ways to do reparsing, working ut how to handle non-parsing, that sort of carry on - all in all a very large amount of work!

**Comment by AgingHippie** [comment]
I thought I was recommending all that stuff as enhancements to ApexDoc itself, not a plugin.  Guess I got lost in the forums here, sorry about that.

**Pull request closed without merging**
